trigger: none

pool: Default

stages:
  - stage: buildanddeploy
    jobs:
      - job: 
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'docker_latest1'
            command: 'login'
        
        - task: CmdLine@2
          inputs:
            script: |
              docker --version
              
              dir
        
        - task: Docker@2
          inputs:
            containerRegistry: 'docker_latest1'
            repository: '2025containerregistry'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            buildContext: '$(System.DefaultWorkingDirectory)'